### ISSUE TITLE
Incorrect type for visitStartSeconds

### ISSUE THREAD

**Issue by sandhub** [llooker/google_ga360#1]
In the [Google Analytics block](https://github.com/llooker/google_ga360/blob/dev-dillon-morrison-ycx9/ga_block.view.lkml#L139), the type for `visitStartSeconds` is specified as date whereas it should be `number`. This is causing the function [TIMESTAMP_MILLIS](https://github.com/llooker/google_ga360/blob/dev-dillon-morrison-ycx9/ga_block.view.lkml#L139) to throw an error when used. 

Can we please fix this? 

PS: It would be good to provide the community here an option to open PR's so that we can fix any pieces that may be broken. 😄

**Comment by DillonMorrison** [comment]
Thanks! this has been added. We're working on a better way to submit PRs for each Block right now - we're hoping to introduce it in '18.
