### ISSUE TITLE
session id is not unique for sessions that carry across date partitions

### ISSUE THREAD

**Issue by ContrastingSounds** [llooker/google_ga360#16]
It's possible to get wild metric calculations when some sessions carry across date partitions, rending the primary key non-unique:

![image](https://user-images.githubusercontent.com/8075115/41650245-7dc04206-7475-11e8-984a-15ade9ff8d07.png)

Temporary applied for NotOnTheHighStreet trial:
https://github.com/llooker/notonthehighstreet_bq/commit/79069704cd715b564fb163898379f05bdbf05e20#diff-16ecbaef51b22a0612e458d6b5c161aa

Note: depending on other metric definitions (eg session counts), the quick fix for NotOnTheHighStreet may not solve the issue entirely.

**Comment by ceckert** [comment]
I am having the same issue. @ContrastingSounds Do you have a PR that addresses this issue that you could share provide the diff above as part of this issue? I don't have permission to the link you posted in the issue report. Thanks.

**Comment by DillonMorrison** [comment]
@ContrastingSounds  @ceckert -- thank you guys for surfacing this. Something changed with how GA exports their cross-day visits. We can make this a primary key by adding partition_date. I'm submitting a fix right now!

**Comment by DillonMorrison** [comment]
this is fixed now! notice the addition to the primary_key in the ga_block view.
