### ISSUE TITLE
syntax in comments did not work for bringing in custom dimensions

### ISSUE THREAD

**Issue by ContrastingSounds** [llooker/google_ga360#17]
When trying to add new custom dimensions for NotOnTheHighStreet trial, the commented-out syntax in the commets of ga_customize.lkml did not work for me.

I used this syntax, and updated the comments in their GA block to suit:

dimension: custom_dimension_1 {
   sql: (SELECT value FROM UNNEST(${hits.customDimensions}) WHERE index=1) ;;
}

https://github.com/llooker/notonthehighstreet_bq/commit/12ac7591b35306940ceff0fb6b3076d010cf0668#diff-d450f10ad3571a6838fd1ac384df9895

**Comment by DillonMorrison** [comment]
@ContrastingSounds thanks for this! I'll update the main Block with the corrected syntax.
