### ISSUE TITLE
isMobile can . not be filtered

### ISSUE THREAD

**Issue by gerardwhite** [llooker/google_ga360#19]
Fix:

`  dimension: isMobile {label: "Is Mobile"}
`
should be updated to

`  dimension: isMobile {label: "Is Mobile" type: yesno}
`

**Comment by ernestoongaro** [comment]
closed in https://github.com/llooker/google_ga360/commit/6227135d4725ead7d6ad2b8fccb15eac923c0869

**Comment by bshreve** [comment]
According to Google's docs, this field is deprecated and device.deviceCategory should be used instead.

[https://support.google.com/analytics/answer/3437719?hl=en](https://support.google.com/analytics/answer/3437719?hl=en)

> device.isMobile
> This field is deprecated. Use device.deviceCategory instead.

**Comment by ernestoongaro** [comment]
@finlbi yup, I re-implemented https://github.com/llooker/google_ga360/commit/6227135d4725ead7d6ad2b8fccb15eac923c0869
