### ISSUE TITLE
Session counts using Looker block are not matching with GA 360 portal counts

### ISSUE THREAD

**Issue by SrikarWMT** [llooker/google_ga360#25]

**Comment by bshreve** [comment]
Looker states that there may be a 1-2% discrepancy between the GA UI and GA export in BQ. Source:
https://github.com/llooker/google_ga360#notes-and-other-known-issues

However, we're using the Looker GA block and our session and user counts are usually spot on. I just checked our portal against the BQ export data and found an exact match in the session count for yesterday. Make sure to filter to hits.isInteraction = 1 and ensure you're summing distinct sessions.

```
CASE WHEN hits.isInteraction THEN 'Yes' ELSE 'No' END
 AS hits_isinteraction_1,
	COUNT(DISTINCT CONCAT(CAST(ga_sessions.fullVisitorId AS STRING), '|', COALESCE(CAST(ga_sessions.visitId AS STRING),''), '|',CAST(ga_sessions.date AS STRING)) ) AS ga_sessions_session_count
```

**Comment by SrikarWMT** [comment]
@finlbi I can not thank you more for above information. You made my day.
I did the changes you suggested and counts are matching just like you said. Could you please share the condition for users count as well.

Thanks once again

**Comment by SrikarWMT** [comment]
Hi @finlbi 

Could you please let me know how are you reconciling user counts.

Regards,
Srikar

**Comment by bshreve** [comment]
@SrikarWMT Our user counts match the GA UI when there is no filter applied to hits.isInteraction. It looks like Google is simply counting the distinct values in the fullVisitorID field.

`COUNT(DISTINCT(fullVisitorId ))`

**Comment by SrikarWMT** [comment]
Thanks @finlbi for the reply regarding User counts. 
I understand that there 2 to 3% discrepancy in user counts when compared to GA 360 portal. 
I would like to know if the same discrepancy applies to Unique page views as well. 
I could match below KPIs precisely but not unique page views. Do i need to apply any filter/condition to match this Unique page views KPI.

*Session
*Conversion Rate
*PageViews
*Bounce Rate

**Comment by ernestoongaro** [comment]
Thanks @finlbi for finding this! I've confirmed it with another GA customer
